### ISSUE TITLE
Licence of the Repo

### ISSUE THREAD

**Issue by jontok** [dargmuesli/jonas-thelemann#142]
Could you please add a LICENSE to your project.

I would like to use it.

**Comment by jontok** [comment]
Sorry wrong repo. I was looking for your creal.

**Comment by dargmuesli** [comment]
Added one anyway, thanks! btw, what are you willing to use dargmuesli/creal for? An own DJ website? :)

**Comment by jontok** [comment]
I want to use it as a Website for a DJ Collective.

**Comment by dargmuesli** [comment]
Nice, I'd be happy to have a look at it once deployed.
