### ISSUE TITLE
feat: add contact form

### ISSUE THREAD

**Issue by dargmuesli** [dargmuesli/jonas-thelemann#286]
Instead of exposing an email address.

**Comment by SonolaMoyo** [comment]
Hi @dargmuesli, I'm participating in hacktoberfest2023 and I'll let to take up this issue and resolve it. Kindly assign the issue to me, thanks and expect a resolve as soon as possible.

**Comment by dargmuesli** [comment]
Hey @SonolaMoyo, thank you for offering help! I'm surprised that this issue is still open because I resolved it recently already (https://github.com/dargmuesli/jonas-thelemann/pull/337). It seems I forgot to link to this issue, sorry! :pray: 
Instead, I'd recommend to check out [maevsi's issues tagged as #hacktoberfest](https://github.com/maevsi/maevsi/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest) for which I'll happily provide assistance in resolving! :raised_hands: 
Check out https://github.com/maevsi/ to find a link to our Discord where we can discuss the details :heart:
